name = "cf-ai-latency"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "latency_db"
database_id = "501d459c-f903-41c5-b7ca-dc6f22e272ca"

# Secrets Store
[[secrets_store_secrets]]
store_id = "3d8f0f9a2a254f05b9de77ec1c6923fb"
binding = "SECRET"
secret_name = "latency"

# AI binding
[ai]
binding = "AI"
