name = "cf-ai-latency"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"



# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "latency_db"
database_id = "501d459c-f903-41c5-b7ca-dc6f22e272ca"

# AI binding
[ai]
binding = "AI"
