name = "cf-ai-latency"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]

# Pages build configuration
pages_build_output_dir = ".open-next/assets"

# OpenNext configuration for Cloudflare Workers
main = ".open-next/worker.js"
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "latency_db"
database_id = "501d459c-f903-41c5-b7ca-dc6f22e272ca"

# AI binding
[ai]
binding = "AI"
